apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clusterregistries.operator.federation.k8s.io
spec:
  group: operator.federation.k8s.io
  names:
    kind: ClusterRegistry
    listKind: ClusterRegistryList
    plural: clusterregistries
    singular: clusterregistry
  scope: Namespaced
  version: v1alpha1
