apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: federationv2.v0.0.2
spec:
  install:
    strategy: deployment
    spec:
      permissions:
      - serviceAccountName: federation-v2-operator
        rules:
        - apiGroups:
          - core.federation.k8s.io
          resources:
          - "*"
          verbs:
          - "*"
        - apiGroups:
          - multiclusterdns.federation.k8s.io
          resources:
          - "*"
          verbs:
          - "*"
        - apiGroups:
          - scheduling.federation.k8s.io
          resources:
          - "*"
          verbs:
          - "*"
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - "*"
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - "*"
      # TODO(font): use statefulset
      deployments:
      # TODO(font): consider best name for this controller-manager/operator deployment
      - name: federation-v2-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: federation-v2-operator
          template:
            metadata:
              labels:
                app: federation-v2-operator
            spec:
              containers:
                - name: federation-v2-operator-olm-owned
                  image: quay.io/kubernetes-multicluster/federation-v2:canary
                  resources:
                    limits:
                      cpu: 100m
                      memory: 128Mi
                    requests:
                      cpu: 100m
                      memory: 64Mi
                  command:
                    - /root/controller-manager
                  args:
                    - --install-crds=false
                  imagePullPolicy: Always
                  env:
                  - name: MY_POD_NAMESPACE
                    valueFrom:
                      fieldRef:
                        fieldPath: metadata.namespace
                  - name: MY_POD_NAME
                    valueFrom:
                      fieldRef:
                        fieldPath: metadata.name
                  - name: WATCH_NAMESPACE
                    valueFrom:
                      fieldRef:
                        fieldPath: metadata.namespace
                  - name: OPERATOR_NAME
                    value: "federation-v2-operator"
              restartPolicy: Always
              terminationGracePeriodSeconds: 5
              serviceAccountName: federation-v2-operator
              serviceAccount: federation-v2-operator
  customresourcedefinitions:
    required:
      - description: Represents an instance of a Cluster Registry
        displayName: Cluster Registry Application
        kind: Cluster
        name: clusters.clusterregistry.k8s.io
        version: v1alpha1
    owned:
      - description: Represents an instance of a FederatedCluster resource
        displayName: FederatedCluster Resource
        kind: FederatedCluster
        name: federatedclusters.core.federation.k8s.io
        version: v1alpha1
      - description: Represents an instance of a FederatedConfigMap resource
        displayName: FederatedConfigMap Resource
        kind: FederatedConfigMap
        name: federatedconfigmaps.core.federation.k8s.io
        version: v1alpha1
      - description: Represents an instance of a FederatedConfigMapOverride resource
        displayName: FederatedConfigMapOverride Resource
        kind: FederatedConfigMapOverride
        name: federatedconfigmapoverrides.core.federation.k8s.io
        version: v1alpha1
      - description: Represents an instance of a FederatedConfigMapPlacement resource
        displayName: FederatedConfigMapPlacement Resource
        kind: FederatedConfigMapPlacement
        name: federatedconfigmapplacements.core.federation.k8s.io
        version: v1alpha1
      - description: Represents an instance of a FederatedDeployment resource
        displayName: FederatedDeployment Resource
        kind: FederatedDeployment
        name: federateddeployments.core.federation.k8s.io
        version: v1alpha1
      - description: Represents an instance of a FederatedDeploymentOverride resource
        displayName: FederatedDeploymentOverride Resource
        kind: FederatedDeploymentOverride
        name: federateddeploymentoverrides.core.federation.k8s.io
        version: v1alpha1
      - description: Represents an instance of a FederatedDeploymentPlacement resource
        displayName: FederatedDeploymentPlacement Resource
        kind: FederatedDeploymentPlacement
        name: federateddeploymentplacements.core.federation.k8s.io
        version: v1alpha1
      - description: Represents an instance of a FederatedIngress resource
        displayName: FederatedIngress Resource
        kind: FederatedIngress
        name: federatedingresses.core.federation.k8s.io
        version: v1alpha1
      - description: Represents an instance of a FederatedIngressPlacement resource
        displayName: FederatedIngressPlacement Resource
        kind: FederatedIngressPlacement
        name: federatedingressplacements.core.federation.k8s.io
        version: v1alpha1
      - description: Represents an instance of a FederatedJob resource
        displayName: FederatedJob Resource
        kind: FederatedJob
        name: federatedjobs.core.federation.k8s.io
        version: v1alpha1
      - description: Represents an instance of a FederatedJobOverride resource
        displayName: FederatedJobOverride Resource
        kind: FederatedJobOverride
        name: federatedjoboverrides.core.federation.k8s.io
        version: v1alpha1
      - description: Represents an instance of a FederatedJobPlacement resource
        displayName: FederatedJobPlacement Resource
        kind: FederatedJobPlacement
        name: federatedjobplacements.core.federation.k8s.io
        version: v1alpha1
      - description: Represents an instance of a FederatedNamespacePlacement resource
        displayName: FederatedNamespacePlacement Resource
        kind: FederatedNamespacePlacement
        name: federatednamespaceplacements.core.federation.k8s.io
        version: v1alpha1
      - description: Represents an instance of a FederatedReplicaSet resource
        displayName: FederatedReplicaSet Resource
        kind: FederatedReplicaSet
        name: federatedreplicasets.core.federation.k8s.io
        version: v1alpha1
      - description: Represents an instance of a FederatedReplicaSetOverride resource
        displayName: FederatedReplicaSetOverride Resource
        kind: FederatedReplicaSetOverride
        name: federatedreplicasetoverrides.core.federation.k8s.io
        version: v1alpha1
      - description: Represents an instance of a FederatedReplicaSetPlacement resource
        displayName: FederatedReplicaSetPlacement Resource
        kind: FederatedReplicaSetPlacement
        name: federatedreplicasetplacements.core.federation.k8s.io
        version: v1alpha1
      - description: Represents an instance of a FederatedSecret resource
        displayName: FederatedSecret Resource
        kind: FederatedSecret
        name: federatedsecrets.core.federation.k8s.io
        version: v1alpha1
      - description: Represents an instance of a FederatedSecretOverride resource
        displayName: FederatedSecretOverride Resource
        kind: FederatedSecretOverride
        name: federatedsecretoverrides.core.federation.k8s.io
        version: v1alpha1
      - description: Represents an instance of a FederatedSecretPlacement resource
        displayName: FederatedSecretPlacement Resource
        kind: FederatedSecretPlacement
        name: federatedsecretplacements.core.federation.k8s.io
        version: v1alpha1
      - description: Represents an instance of a FederatedService resource
        displayName: FederatedService Resource
        kind: FederatedService
        name: federatedservices.core.federation.k8s.io
        version: v1alpha1
      - description: Represents an instance of a FederatedServicePlacement resource
        displayName: FederatedServicePlacement Resource
        kind: FederatedServicePlacement
        name: federatedserviceplacements.core.federation.k8s.io
        version: v1alpha1
      - description: Represents an instance of a FederationV2 FederatedType controller
        displayName: FederationV2 Push Reconciler Application
        kind: FederatedTypeConfig
        name: federatedtypeconfigs.core.federation.k8s.io
        version: v1alpha1
      - description: Represents an instance of a PropagatedVersion resource
        displayName: PropagatedVersion Resource
        kind: PropagatedVersion
        name: propagatedversions.core.federation.k8s.io
        version: v1alpha1
      - description: Represents an instance of a DNSEndpoint resource
        displayName: DNSEndpoint Resource
        kind: DNSEndpoint
        name: dnsendpoints.multiclusterdns.federation.k8s.io
        version: v1alpha1
      - description: Represents an instance of a MultiClusterIngressDNSRecord resource
        displayName: MultiClusterIngressDNSRecord Resource
        kind: MultiClusterIngressDNSRecord
        name: multiclusteringressdnsrecords.multiclusterdns.federation.k8s.io
        version: v1alpha1
      - description: Represents an instance of a MultiClusterServiceDNSRecord resource
        displayName: MultiClusterServiceDNSRecord Resource
        kind: MultiClusterServiceDNSRecord
        name: multiclusterservicednsrecords.multiclusterdns.federation.k8s.io
        version: v1alpha1
      - description: Represents an instance of a ReplicaSchedulingPreference resource
        displayName: ReplicaSchedulingPreference Resource
        kind: ReplicaSchedulingPreference
        name: replicaschedulingpreferences.scheduling.federation.k8s.io
        version: v1alpha1
  version: 0.0.2
  displayName: FederationV2
  labels:
    olm-owner-enterprise-app: federation-v2-operator
    olm-status-descriptors: federationv2.v0.0.2
