apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: federationv2s.operator.federation.k8s.io
spec:
  group: operator.federation.k8s.io
  names:
    kind: FederationV2
    listKind: FederationV2List
    plural: federationv2s
    singular: federationv2
  scope: Namespaced
  version: v1alpha1
