apiVersion: apps/v1
# TODO(font): use statefulset
kind: Deployment
metadata:
  # TODO(font): consider best name for this controller-manager/operator deployment
  name: federation-controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      name: federation-controller-manager
  template:
    metadata:
      labels:
        name: federation-controller-manager
    spec:
      containers:
        - name: federation-controller-manager
          image: quay.io/kubernetes-multicluster/federation-v2:v0.0.2-rc.1
          ports:
          - containerPort: 60000
            name: metrics
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 64Mi
          command:
            - /root/controller-manager
          args:
            - --federation-namespace=$(FEDERATION_NAMESPACE)
            - --install-crds=false
            - --limited-scope=false
            - --registry-namespace=$(CLUSTER_REGISTRY_NAMESPACE)
          imagePullPolicy: Always
          # TODO(font): Replace with namespace env vars for federation controller manager.
          env:
            - name: FEDERATION_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CLUSTER_REGISTRY_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      serviceAccountName: federation-controller-manager
