apiVersion: apps/v1
# TODO(font): use statefulset
kind: Deployment
metadata:
  # TODO(font): consider best name for this controller-manager/operator deployment
  name: federation-controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      name: federation-controller-manager
  template:
    metadata:
      labels:
        name: federation-controller-manager
    spec:
      containers:
        - name: federation-controller-manager
          image: quay.io/kubernetes-multicluster/federation-v2:canary
          ports:
          - containerPort: 60000
            name: metrics
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 64Mi
          command:
            - /root/controller-manager
          args:
            - --install-crds=false
          imagePullPolicy: Always
          # TODO(font): Replace with namespace env vars for federation controller manager.
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "federation-controller-manager"
      serviceAccountName: federation-controller-manager
