apiVersion: v1
kind: ServiceAccount
metadata:
  name: federation-controller-manager

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: federation-controller-manager
rules:
- apiGroups:
  - clusterregistry.k8s.io
  resources:
  - clusters
  verbs:
  - "*"
- apiGroups:
  - core.federation.k8s.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - multiclusterdns.federation.k8s.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - scheduling.federation.k8s.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: default-account-federation-controller-manager
subjects:
- kind: ServiceAccount
  name: federation-controller-manager
roleRef:
  kind: Role
  name: federation-controller-manager
  apiGroup: rbac.authorization.k8s.io
